module.exports = {
  NOTIFICATION_TYPES: {
    SUBMISSION_PENDING: 'SUBMISSION_PENDING',
    REMOVAL_PENDING: 'REMOVAL_PENDING',
    SUBMISSION_ACCEPTED: 'SUBMISSION_ACCEPTED',
    REMOVAL_ACCEPTED: 'REMOVAL_ACCEPTED',
    SUBMISSION_CHALLENGED: 'SUBMISSION_CHALLENGED',
    REMOVAL_CHALLENGED: 'REMOVAL_CHALLENGED',
    EVIDENCE_SUBMITTED: 'EVIDENCE_SUBMITTED',
    APPEALED: 'APPEALED',
    APPEALABLE_RULING: 'APPEALABLE_RULING',
    FINAL_RULING: 'FINAL_RULING'
  },
  ITEM_STATUS: {
    ABSENT: 0,
    REGISTERED: 1,
    REGISTRATION_REQUESTED: 2,
    REMOVAL_REQUESTED: 3
  }
}
